bots:
  claude:
    api_key_env: ANTHROPIC_API_KEY
    discord_token_env: DISCORD_TOKEN_CLAUDE
    enabled: false
    llm_model: claude-3-opus-20240229
    llm_provider: anthropic
    max_context_messages: 20
    name: Claude Assistant
    personality: 'You are Claude, a thoughtful and analytical AI assistant.

      You excel at code analysis and complex reasoning tasks.

      '
    response_delay: 1.5
    trigger_words:
    - claude
    - hey claude
  gpt:
    api_key_env: OPENAI_API_KEY
    discord_token_env: DISCORD_TOKEN_GPT
    enabled: false
    llm_model: gpt-4.1
    llm_provider: openai
    max_context_messages: 10
    name: GPT Assistant
    personality: 'You are a helpful OpenAI assistant powered by GPT-4.

      You can help with a wide range of tasks.

      '
    response_delay: 1
    trigger_words:
    - gpt
    - chatgpt
  grok4:
    api_key_env: XAI_API_KEY
    discord_token_env: DISCORD_TOKEN_GROK4
    enabled: true
    llm_model: grok-4-latest
    llm_provider: xai
    max_context_messages: 15
    name: Grok4 Assistant
    personality: 'You are Grok4, a helpful and slightly witty AI assistant.

      You have access to live data and can engage in technical discussions.

      '
    response_delay: 0
    trigger_words:
    - grok
    - hey grok
global:
  database:
    cleanup_interval_hours: 24
    max_message_age_days: 90
  monitoring:
    health_check_interval: 30
    metrics_enabled: false
    metrics_port: 9090
  rate_limiting:
    max_requests_per_minute: 30
    max_requests_per_user_per_minute: 5
